global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'notification-user-app'
    metrics_path: '/api/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
  - job_name: 'notification-auth-app'
    metrics_path: '/api/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081']